### ISSUE TITLE
無法更新實驗室

### ISSUE THREAD

**Issue by abc10324** [abc10324/smart-fermentation-tank-api#1]
Endpoint : PUT http://180.214.179.92:7060/api/laboratory/659a5588a498c30c39b732e7
Request Body :

`
  {
    "id": "659a5588a498c30c39b732e7",
    "createTime": "2024/01/07 15:39",
    "createUser": "659a346cece0161873be3560",
    "updateTime": "2024/01/07 15:39",
    "updateCount": 0,
    "ownerId": "659a553d2e55e076f115ca6d",
    "name": "LabA",
    "note": "123",
    "status": "ACTIVE",
    "memberList": [
      {
        "id": "65d06def8c6e4a371c02c3a9",
        "createTime": "2024/02/17 16:27",
        "createUser": "659a553d2e55e076f115ca6d",
        "updateTime": "2024/02/17 16:27",
        "updateCount": 1,
        "account": "abc10324U",
        "role": "LAB_USER",
        "name": "LabUser",
        "email": "abc@abc",
        "labList": [
          "659a5588a498c30c39b732e7"
        ],
        "labNameList": [],
        "status": "ACTIVE",
        "loginCount": 0,
        "lastLoginTime": null,
        "statusName": "啟用"
      }
    ]
  }
`

Response : 
`
  {
    "code": "E002",
    "cause": "無法更新不存在的實驗室"
  }
`

**Comment by JoyceLIN0811** [comment]
no! 資料沒有status
