### ISSUE TITLE
實驗室更新有錯誤訊息並且無法更新

### ISSUE THREAD

**Issue by abc10324** [abc10324/smart-fermentation-tank-api#4]
`
{
    "code": "E000",
    "cause": "Write operation error on server db:27017. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: smart-fermentation-tank.laboratory index: _id_ dup key: { _id: ObjectId('659a5588a498c30c39b732e7') }', details={}}."
}
`

**Comment by JoyceLIN0811** [comment]
done
