### ISSUE TITLE
LineNotify顯示因權限無法更新

### ISSUE THREAD

**Issue by abc10324** [abc10324/smart-fermentation-tank-api#7]
https://github.com/abc10324/smart-fermentation-tank-api/blob/794180141d92d5744091b549ed737c19ecae030e/src/main/java/com/walnutek/fermentationtank/controller/LineNotifyController.java#L136-L137

equals裡面吃的是Object所以這邊不會報錯, 但你應該給他真正的userId, 而不是AuthUser物件

**Comment by JoyceLIN0811** [comment]
done
