### ISSUE TITLE
LineNotify註冊被登入interceptor擋住了

### ISSUE THREAD

**Issue by abc10324** [abc10324/smart-fermentation-tank-api#8]
https://github.com/abc10324/smart-fermentation-tank-api/blob/794180141d92d5744091b549ed737c19ecae030e/src/main/java/com/walnutek/fermentationtank/config/auth/AuthConfig.java#L49

這邊不用加/api , 如實寫上Controller裡面寫的路徑即可

**Comment by JoyceLIN0811** [comment]
done
