### ISSUE TITLE
權限標示的太多了，請標註需要標註的即可

### ISSUE THREAD

**Issue by abc10324** [abc10324/smart-fermentation-tank-api#9]
https://github.com/abc10324/smart-fermentation-tank-api/blob/d9fe0956cca28a378b61cd51b5c39aae213e6533/src/main/java/com/walnutek/fermentationtank/controller/UserController.java#L56

此為其中一隻供參考，實驗室員工因此API無法登入

**Comment by JoyceLIN0811** [comment]
已刪除不必要的標註
